version: '3.3'

services:
  app:
    container_name: fiap-pos-tech-docker-app
    image: supwr/fiap-programming-languages:latest
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8000:8000
    networks:
      - fiap-pos-tech
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: fiap-pos-tech-docker-db
    image: postgres:latest
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - fiap-pos-tech

volumes:
  postgres_data:

networks:
  fiap-pos-tech:
